### ISSUE TITLE
Error during sbt execution: Duplicate label 'directory' in section 'boot'

### ISSUE THREAD

**Issue by clasnake** [foundweekends/conscript#101]
Hello, I encountered this error when installing conscript. Any suggestions on this?
What I did is run curl https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh | sh
and copy sbt-launch.jar into ~/.conscript/

**Comment by eed3si9n** [comment]
> What I did is run curl https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh | sh
and copy sbt-launch.jar into ~/.conscript/

Why did you have to sbt-launch.jar? Did the setup script not download the launcher jar in the right place?

Also could you copy-paste your launchconfig file here?

**Comment by clasnake** [comment]
Ah it turns out my wget didn't work correctly and failed to download the launcher jar. I've updated my wget and it works now. Sorry for that and this issue can be closed now. Thanks.

**Comment by eed3si9n** [comment]
ok
