### ISSUE TITLE
gh page for conscript 

### ISSUE THREAD

**Issue by softprops** [foundweekends/conscript#36]
...because I forgot how awesome you graphic is for this. I love it.

 I was thinking about how I might be able to capture some of this with `ls`. I might just start capturing a `type` or `kind` property that describes what kind of library a project is. Since you don't really install conscripts with `foo %% bar % baz` and versions dont really matter /w cs, maybe I'll build something different.  I'd like to build something similar to `ls` that captures a simple markdown description of what the conscript does and serve up jsonp api that can be consumed by a static gh page with a style tailored to that awesome logo of yours. This would also tie in nicely with something else I've got simmering in the kitchen. I'm writing this down now so I don't forget and so that it actually gets done. Right now it's not easy to find conscripts but I know they are out there. I want to make them so.

Conscript may actually be a cool, albiet short, topic for nescala. Just sayin'.

**Comment by eed3si9n** [comment]
There's now a pamflet for conscript - http://www.foundweekends.org/conscript/conscripted-apps.html
