### ISSUE TITLE
Change installation paths on Linux

### ISSUE THREAD

**Issue by psychoticmeow** [foundweekends/conscript#55]
At the moment conscript adds two ? more directories to my home folder:
```
bin/
.conscript
```

However it's impolite to add directories into the home folder, it would be better if conscript could use the following directories instead (this is at least correct for Arch Linux):

```
.local/bin
.config/conscript
```

Or at least allow us the choice on installation.

**Comment by iamale** [comment]
:+1:

**Comment by xuwei-k** [comment]
fixed by https://github.com/foundweekends/conscript/commit/21724b03c4615dd77b56a0d914d933a2d460fb16

**Comment by iamale** [comment]
@xuwei-k @eed3si9n Great! Although would be better if user also cound choose the bin directory (i. e. like so: `CONSCRIPT_HOME="$HOME/.local/conscript" CONSCRIPT_PATH="$HOME/.local/bin"`).

**Comment by eed3si9n** [comment]
@iamale I added `CONSCRIPT_BIN` too.

**Comment by iamale** [comment]
Oh, awesome! Why not mention it in the readme maybe?
